import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import $ from "jquery";
// import {} from "inputmask";
import { useEffect } from "react";
import CustomSlider from "../components/Slider";
import Advantages from "../components/Advantages";

export default function Home() {
  useEffect(() => {
    // Modal
    $(".form_disable input, .form_disable textarea").on("keyup", function () {
      var parent = $(this).parents(".form_disable");
      var success = true;
      var btn = $(parent).find(".btn");
      var input = $(parent).find("input");
      var textarea = $(parent).find("textarea");
      $(input, textarea).each(function () {
        var reg = $(this).attr("required");
        if (reg && $(this).val() == "") {
          success = false;
        }

        if (reg && $(this).hasClass("tel") && $(this).val() != "") {
          var num = $(this).val().replace(/\D/g, "");
          if (num.length != 11) {
            success = false;
          }
        }
      });
      if (success) {
        $(btn).prop("disabled", false);
      } else {
        $(btn).prop("disabled", true);
      }
    });

    $(".open--modal").on("click", function () {
      var link = $(this).attr("data-modal");
      $(link).fadeIn();
      return false;
    });
    $(".open--modal2").on("click", function () {
      var link = $(this).attr("data-modal");
      $(link).fadeIn();
      return false;
    });

    $(".modal .close, .modal__layer").on("click", function () {
      $(this).parents(".modal, .mobile-contacts").fadeOut();
      return false;
    });

    // // Scroll to top
    // if ($(".back-to-top").length) {
    //   var scrollTrigger = 100, // px
    //     backToTop = function () {
    //       var scrollTop = $(window).scrollTop();
    //       if (scrollTop > scrollTrigger) {
    //         $(".back-to-top").addClass("show");
    //       } else {
    //         $(".back-to-top").removeClass("show");
    //       }
    //     };
    //   backToTop();

    //   $(window).on("scroll", function () {
    //     backToTop();
    //   });
    //   $(".back-to-top").on("click", function (e) {
    //     e.preventDefault();
    //     $("html,body").animate(
    //       {
    //         scrollTop: 0,
    //       },
    //       700
    //     );
    //   });
    // }

    // menu
    $(function () {
      $(".menu--btn").on("click", function () {
        var menu = document.querySelector("header .menu");
        if ($(menu).is(":visible")) {
          $(menu).slideUp();
          $(this).removeClass("open");
        } else {
          $(menu).slideDown();
          $(this).addClass("open");
        }
        return false;
      });
    });

    // phone
    $(function () {
      $(".phone--btn").on("click", function () {
        var phone = document.querySelector("header .phone");
        if ($(phone).is(":visible")) {
          $(phone).slideUp();
          $(this).removeClass("close");
        } else {
          $(phone).slideDown();
          $(this).addClass("close");
        }
        return false;
      });

      $(".social--btn").on("click", function () {
        var social = document.querySelector("header .social");
        $(social).slideDown();
        $(document).bind("touchstart", function (e) {
          if (!e.target.closest("header .social")) {
            $("header .social").slideUp();
          }
          e.stopPropagation();
        });
        return false;
      });
    });

    //
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <CustomSlider />
        <Advantages />
      </section>
    </div>
  );
}
